spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5000/realms/spring-cloud-vitelco-realm
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products**
          filters:
            - SetPath=/v1/products
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders**
          filters:
            - SetPath=/v1/orders
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventories**
          filters:
            - SetPath=/v1/inventory


server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
