spring:
  application:
    name: order-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5431/postgres
    type: org.postgresql.ds.PGPoolingDataSource
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 15
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 4001
