spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/products-service
      database: productsDb
server:
  port: 4000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
